### ISSUE TITLE
5.4.1 causes AttributeError: SQLCompiler object has no attribute '_execute_sql'

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [jazzband/django-silk#817]
After updating the silk version to 5.4.1, all of a sudden I started getting a lot of Attribute Errors for almost all the queries. It says that the method _execute_sql does not exist for SQLCompiler/SQLAggregateCompiler objects

**Comment by samueljansem** [comment]
I'm facing the same problem here.
- django 5.1.11
- django-silk 5.4.1

```
 [silk.profiling.profiler] [ERROR] Exception when performing meta profiling, dumping trace below
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/silk/middleware.py", line 158, in _process_response
     collector.finalise()
   File "/usr/local/lib/python3.11/site-packages/silk/collector.py", line 167, in finalise
     models.SQLQuery.objects.bulk_create(sql_queries)
   File "/usr/local/lib/python3.11/site-packages/silk/models.py", line 238, in bulk_create
     obj.prepare_save()
   File "/usr/local/lib/python3.11/site-packages/silk/models.py", line 323, in prepare_save
     self.request.save(update_fields=['num_sql_queries'])
   File "/usr/local/lib/python3.11/site-packages/silk/models.py", line 195, in save
     super().save(*args, **kwargs)
   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save
     self.save_base(
   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 998, in save_base
     updated = self._save_table(
               ^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1130, in _save_table
     updated = self._do_update(
               ^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1195, in _do_update
     return filtered._update(values) > 0
            ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1278, in _update
     return query.get_compiler(self.db).execute_sql(CURSOR)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
     cursor = super().execute_sql(result_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/silk/sql.py", line 97, in execute_sql
     return self._execute_sql(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^
```
